name: chexpert-label
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0=mkl
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py36_0
  - decorator=4.3.0=py_0
  - docopt=0.6.2=py_1
  - gcc_linux-64=7.3.0=h553295d_9
  - gxx_linux-64=7.3.0=h553295d_9
  - intel-openmp=2019.1=144
  - jpype1=0.6.3=py36h9de70de_1001
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_5
  - liblapack=3.8.0=14_mkl
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - mkl=2019.1=144
  - mkl_fft=1.0.6=py36_0
  - mkl_random=1.0.1=py36_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=1.11=py36_0
  - nltk=3.3.0=py36_0
  - numpy=1.15.4=py36h8b7e671_1002
  - numpy-base=1.15.4=py36hde5b4d6_0
  - openssl=1.1.1f=h7b6447c_0
  - pandas=0.23.4=py36h637b7d7_1000
  - pathlib2=2.3.5=py36_0
  - pip=18.1=py36_1000
  - ply=3.11=py_1
  - python=3.6.7=h0371630_0
  - python-dateutil=2.7.5=py_0
  - pytz=2018.7=py_0
  - readline=7.0=hf8c457e_1001
  - setuptools=40.6.2=py36_0
  - six=1.11.0=py36_1001
  - sqlite=3.25.3=h67949de_1000
  - tk=8.6.8=h84994c4_1000
  - tqdm=4.28.1=py_0
  - wheel=0.32.3=py36_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - pip:
    - bioc==1.1.dev3
    - bllipparser==2016.9.11
    - deprecation==2.0.6
    - docutils==0.13.1
    - lxml==3.7.3
    - packaging==18.0
    - pyparsing==2.3.0
    - pystanforddependencies==0.3.1

